# docker-compose.yml
version: '3.0'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    entrypoint: /daangn-server/entrypoint.sh
    command: ["rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/daangn-server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PG_PASSWORD: password
